#!/usr/bin/bash

if [ "$#" -gt 1 ]; then
    echo -ne "  Usage: user_prompt [YES_NO_QUESTION]\n"
    exit 1
fi

YES_NO_QUESTION="Continue?"
if [ "$#" -eq 1 ]; then
    YES_NO_QUESTION=$1
fi

read -p "$YES_NO_QUESTION (y/[n]) " res

case $res in
    y ) exit 0;;
    * ) exit 1;;
esac
