#!/usr/bin/bash
BASEDIR=$(pwd)

exec 3>&2
exec 2> /dev/null
GITDIR=$(git -C $BASEDIR rev-parse --git-dir)
exec 2>&3

if [ "$GITDIR" == "" ] && [ ! -d $GITDIR ]; then
    echo "$BASEDIR is not part of a git directory"
    exit 1
fi

gstatus() {
    git -C $(dirname $GITDIR) submodule foreach 'git status -s'
    git -C $(dirname $GITDIR) status
}
gcommit() {
    git -C $(dirname $GITDIR) submodule foreach "git add . && git commit -m '$1'"
    git -C $(dirname $GITDIR) add . && git -C $(dirname $GITDIR) commit -m "$1"
}
gpull() {
    git -C $(dirname $GITDIR) submodule foreach 'git pull origin main'
    git -C $(dirname $GITDIR) pull origin main
}
gpush() {
    git -C $(dirname $GITDIR) submodule foreach 'git push origin main'
    git -C $(dirname $GITDIR) push origin main
}

if [ $# -ne 0 ] && [ "$1" == "pull" ]; then
    gpull
elif [ $# -ne 0 ] && [ "$1" == "push" ]; then
    gpush
elif [ $# -ne 0 ] && [ "$1" == "commit" ]; then
    COMMITSTR="autocommit: $USER@$HOSTNAME ($(date +'%Y/%d/%m %T'))"
    #echo $COMMITSTR
    gcommit $COMMITSTR
else
    gstatus
fi

