#!/usr/bin/bash
BASEDIR=$1

exec 3>&2
exec 2> /dev/null
GITDIR=$(git -C $BASEDIR rev-parse --git-dir)
exec 2>&3

if [ "$GITDIR" != "" ] && [ -d $GITDIR ]; then
    git submodule foreach 'git pull origin main'
    git push origin main
else
    echo "$BASEDIR is not part of a git directory"
fi
