#!/usr/bin/bash

if [ "$#" -ne 2 ]; then
    echo -ne "  Usage: read_serial <Device> <Baud>\n"
    exit 1
fi

NAME=$1
BAUD=$2

echo -ne "Device: $1\n"
echo -ne "Baud:   $2\n"
echo -ne "(Read Only)\n\n"

stty -F $NAME ispeed $BAUD
cat $NAME
