set mouse=a

set tabstop=4
set softtabstop=4
set shiftwidth=4

set expandtab
set autoindent
set fileformat=unix

syntax on
set encoding=utf-8
set number
highlight LineNr term=italic cterm=italic gui=italic
highlight Normal guifg=white guibg=black
highlight Normal ctermfg=white ctermbg=black

